$(document).ready(function(){
  $(".mobile-menu").click(function(){
   $("header").toggleClass("active");
  });
});
$(document).ready(function(){
  $(".close").click(function(){
    $(".calendar-hed").toggle();
  });
});